version: '3'
services:
  etcd:
    image: quay.io/coreos/etcd
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    command: >
      /usr/local/bin/etcd
      --name etcd0
      --data-dir /etcd-data
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379
      --listen-peer-urls http://0.0.0.0:2380
      --initial-advertise-peer-urls http://0.0.0.0:2380
      --initial-cluster etcd0=http://0.0.0.0:2380
      --initial-cluster-token etcd-cluster-1
      --initial-cluster-state new
      --max-request-bytes=10485760