// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: pkg/proto/controllerpb/controller.proto

package controllerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateIdRequest) Reset() {
	*x = GenerateIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_controllerpb_controller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdRequest) ProtoMessage() {}

func (x *GenerateIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_controllerpb_controller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdRequest.ProtoReflect.Descriptor instead.
func (*GenerateIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_controllerpb_controller_proto_rawDescGZIP(), []int{0}
}

type GenerateIdReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eid int64 `protobuf:"varint,1,opt,name=eid,proto3" json:"eid,omitempty"`
}

func (x *GenerateIdReply) Reset() {
	*x = GenerateIdReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_controllerpb_controller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateIdReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdReply) ProtoMessage() {}

func (x *GenerateIdReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_controllerpb_controller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdReply.ProtoReflect.Descriptor instead.
func (*GenerateIdReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_controllerpb_controller_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIdReply) GetEid() int64 {
	if x != nil {
		return x.Eid
	}
	return 0
}

var File_pkg_proto_controllerpb_controller_proto protoreflect.FileDescriptor

var file_pkg_proto_controllerpb_controller_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x70, 0x62, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x0f,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x65, 0x69,
	0x64, 0x32, 0x59, 0x0a, 0x09, 0x49, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c,
	0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x12, 0x1f, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x49, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x37, 0x5a, 0x35,
	0x67, 0x69, 0x74, 0x2e, 0x77, 0x6f, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x66, 0x75,
	0x61, 0x69, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x2d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_controllerpb_controller_proto_rawDescOnce sync.Once
	file_pkg_proto_controllerpb_controller_proto_rawDescData = file_pkg_proto_controllerpb_controller_proto_rawDesc
)

func file_pkg_proto_controllerpb_controller_proto_rawDescGZIP() []byte {
	file_pkg_proto_controllerpb_controller_proto_rawDescOnce.Do(func() {
		file_pkg_proto_controllerpb_controller_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_controllerpb_controller_proto_rawDescData)
	})
	return file_pkg_proto_controllerpb_controller_proto_rawDescData
}

var file_pkg_proto_controllerpb_controller_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_controllerpb_controller_proto_goTypes = []interface{}{
	(*GenerateIdRequest)(nil), // 0: controllerpb.GenerateIdRequest
	(*GenerateIdReply)(nil),   // 1: controllerpb.GenerateIdReply
}
var file_pkg_proto_controllerpb_controller_proto_depIdxs = []int32{
	0, // 0: controllerpb.IdService.GenerateId:input_type -> controllerpb.GenerateIdRequest
	1, // 1: controllerpb.IdService.GenerateId:output_type -> controllerpb.GenerateIdReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_controllerpb_controller_proto_init() }
func file_pkg_proto_controllerpb_controller_proto_init() {
	if File_pkg_proto_controllerpb_controller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_controllerpb_controller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_controllerpb_controller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateIdReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_controllerpb_controller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_controllerpb_controller_proto_goTypes,
		DependencyIndexes: file_pkg_proto_controllerpb_controller_proto_depIdxs,
		MessageInfos:      file_pkg_proto_controllerpb_controller_proto_msgTypes,
	}.Build()
	File_pkg_proto_controllerpb_controller_proto = out.File
	file_pkg_proto_controllerpb_controller_proto_rawDesc = nil
	file_pkg_proto_controllerpb_controller_proto_goTypes = nil
	file_pkg_proto_controllerpb_controller_proto_depIdxs = nil
}
