global:
  scrape_interval: 1s
  evaluation_interval: 1s
  
scrape_configs:

- job_name: 'consumer'
  static_configs:
  - targets: ["9.134.78.221:7060"]

- job_name: 'controller'
  static_configs:
  - targets: ["9.134.78.221:6200", "9.134.78.221:6100", "9.134.78.221:6300"]