// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: pkg/proto/consumerpb/consumer.proto

package consumerpb

import (
	routingpb "git.woa.com/kefuai/mini-router/pkg/proto/routingpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumerInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string   `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"` // 所在的group
	HostName  []string `protobuf:"bytes,2,rep,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`    // 需要的host列表
}

func (x *ConsumerInitRequest) Reset() {
	*x = ConsumerInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumerInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerInitRequest) ProtoMessage() {}

func (x *ConsumerInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerInitRequest.ProtoReflect.Descriptor instead.
func (*ConsumerInitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_consumerpb_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumerInitRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *ConsumerInitRequest) GetHostName() []string {
	if x != nil {
		return x.HostName
	}
	return nil
}

type ConsumerInitReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Group *routingpb.Group `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"` // 包含所需host信息的路由表
}

func (x *ConsumerInitReply) Reset() {
	*x = ConsumerInitReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumerInitReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerInitReply) ProtoMessage() {}

func (x *ConsumerInitReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerInitReply.ProtoReflect.Descriptor instead.
func (*ConsumerInitReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_consumerpb_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumerInitReply) GetGroup() *routingpb.Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type RoutingChangeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RoutingChangeRequest) Reset() {
	*x = RoutingChangeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutingChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingChangeRequest) ProtoMessage() {}

func (x *RoutingChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingChangeRequest.ProtoReflect.Descriptor instead.
func (*RoutingChangeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_consumerpb_consumer_proto_rawDescGZIP(), []int{2}
}

type RoutingChangeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeletedEndpoints []string `protobuf:"bytes,1,rep,name=deleted_endpoints,json=deletedEndpoints,proto3" json:"deleted_endpoints,omitempty"` // 删除的endpoint唯一标识(group/host/eid)
	AddedEndpoints   []string `protobuf:"bytes,2,rep,name=added_endpoints,json=addedEndpoints,proto3" json:"added_endpoints,omitempty"`       // 增加的endpoint唯一标识(group/host/eid)
}

func (x *RoutingChangeReply) Reset() {
	*x = RoutingChangeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutingChangeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingChangeReply) ProtoMessage() {}

func (x *RoutingChangeReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingChangeReply.ProtoReflect.Descriptor instead.
func (*RoutingChangeReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_consumerpb_consumer_proto_rawDescGZIP(), []int{3}
}

func (x *RoutingChangeReply) GetDeletedEndpoints() []string {
	if x != nil {
		return x.DeletedEndpoints
	}
	return nil
}

func (x *RoutingChangeReply) GetAddedEndpoints() []string {
	if x != nil {
		return x.AddedEndpoints
	}
	return nil
}

type PullEndpointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoints []string `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
}

func (x *PullEndpointRequest) Reset() {
	*x = PullEndpointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullEndpointRequest) ProtoMessage() {}

func (x *PullEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullEndpointRequest.ProtoReflect.Descriptor instead.
func (*PullEndpointRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_consumerpb_consumer_proto_rawDescGZIP(), []int{4}
}

func (x *PullEndpointRequest) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type PullEndpointReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoints map[string]*routingpb.Endpoint `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *PullEndpointReply) Reset() {
	*x = PullEndpointReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullEndpointReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullEndpointReply) ProtoMessage() {}

func (x *PullEndpointReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_consumerpb_consumer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullEndpointReply.ProtoReflect.Descriptor instead.
func (*PullEndpointReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_consumerpb_consumer_proto_rawDescGZIP(), []int{5}
}

func (x *PullEndpointReply) GetEndpoints() map[string]*routingpb.Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

var File_pkg_proto_consumerpb_consumer_proto protoreflect.FileDescriptor

var file_pkg_proto_consumerpb_consumer_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x70,
	0x62, 0x1a, 0x21, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51, 0x0a, 0x13, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6f,
	0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x68,
	0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3b, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x26, 0x0a, 0x05,
	0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x05, 0x67,
	0x72, 0x6f, 0x75, 0x70, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6a, 0x0a, 0x12,
	0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x11, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x65, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12,
	0x27, 0x0a, 0x0f, 0x61, 0x64, 0x64, 0x65, 0x64, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x61, 0x64, 0x64, 0x65, 0x64, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x33, 0x0a, 0x13, 0x50, 0x75, 0x6c, 0x6c,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0xb2, 0x01,
	0x0a, 0x11, 0x50, 0x75, 0x6c, 0x6c, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x4a, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a,
	0x51, 0x0a, 0x0e, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x70, 0x62, 0x2e, 0x45,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x32, 0x86, 0x02, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4e, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x1f, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x69,
	0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x30, 0x01, 0x12, 0x4e, 0x0a, 0x0c, 0x50,
	0x75, 0x6c, 0x6c, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x63, 0x6f,
	0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x35, 0x5a, 0x33, 0x67,
	0x69, 0x74, 0x2e, 0x77, 0x6f, 0x61, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x65, 0x66, 0x75, 0x61,
	0x69, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x2d, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_consumerpb_consumer_proto_rawDescOnce sync.Once
	file_pkg_proto_consumerpb_consumer_proto_rawDescData = file_pkg_proto_consumerpb_consumer_proto_rawDesc
)

func file_pkg_proto_consumerpb_consumer_proto_rawDescGZIP() []byte {
	file_pkg_proto_consumerpb_consumer_proto_rawDescOnce.Do(func() {
		file_pkg_proto_consumerpb_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_consumerpb_consumer_proto_rawDescData)
	})
	return file_pkg_proto_consumerpb_consumer_proto_rawDescData
}

var file_pkg_proto_consumerpb_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_proto_consumerpb_consumer_proto_goTypes = []interface{}{
	(*ConsumerInitRequest)(nil),  // 0: consumerpb.ConsumerInitRequest
	(*ConsumerInitReply)(nil),    // 1: consumerpb.ConsumerInitReply
	(*RoutingChangeRequest)(nil), // 2: consumerpb.RoutingChangeRequest
	(*RoutingChangeReply)(nil),   // 3: consumerpb.RoutingChangeReply
	(*PullEndpointRequest)(nil),  // 4: consumerpb.PullEndpointRequest
	(*PullEndpointReply)(nil),    // 5: consumerpb.PullEndpointReply
	nil,                          // 6: consumerpb.PullEndpointReply.EndpointsEntry
	(*routingpb.Group)(nil),      // 7: routingpb.Group
	(*routingpb.Endpoint)(nil),   // 8: routingpb.Endpoint
}
var file_pkg_proto_consumerpb_consumer_proto_depIdxs = []int32{
	7, // 0: consumerpb.ConsumerInitReply.group:type_name -> routingpb.Group
	6, // 1: consumerpb.PullEndpointReply.endpoints:type_name -> consumerpb.PullEndpointReply.EndpointsEntry
	8, // 2: consumerpb.PullEndpointReply.EndpointsEntry.value:type_name -> routingpb.Endpoint
	0, // 3: consumerpb.ConsumerService.ConsumerInit:input_type -> consumerpb.ConsumerInitRequest
	2, // 4: consumerpb.ConsumerService.RoutingChange:input_type -> consumerpb.RoutingChangeRequest
	4, // 5: consumerpb.ConsumerService.PullEndpoint:input_type -> consumerpb.PullEndpointRequest
	1, // 6: consumerpb.ConsumerService.ConsumerInit:output_type -> consumerpb.ConsumerInitReply
	3, // 7: consumerpb.ConsumerService.RoutingChange:output_type -> consumerpb.RoutingChangeReply
	5, // 8: consumerpb.ConsumerService.PullEndpoint:output_type -> consumerpb.PullEndpointReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_consumerpb_consumer_proto_init() }
func file_pkg_proto_consumerpb_consumer_proto_init() {
	if File_pkg_proto_consumerpb_consumer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_consumerpb_consumer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumerInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_consumerpb_consumer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumerInitReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_consumerpb_consumer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutingChangeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_consumerpb_consumer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoutingChangeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_consumerpb_consumer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullEndpointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_consumerpb_consumer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullEndpointReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_consumerpb_consumer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_consumerpb_consumer_proto_goTypes,
		DependencyIndexes: file_pkg_proto_consumerpb_consumer_proto_depIdxs,
		MessageInfos:      file_pkg_proto_consumerpb_consumer_proto_msgTypes,
	}.Build()
	File_pkg_proto_consumerpb_consumer_proto = out.File
	file_pkg_proto_consumerpb_consumer_proto_rawDesc = nil
	file_pkg_proto_consumerpb_consumer_proto_goTypes = nil
	file_pkg_proto_consumerpb_consumer_proto_depIdxs = nil
}
